#!/usr/bin/perl

sub usage{

	print "Usage: $0 -domain <domain> -ns1 <nameserver1> -ns2 <nameserver2>",
				"-backup <backup resolv name>\n";
	exit 0;

}

sub create{

	print "Domain: $DOMAIN\n",
	"Backup Name: $BACKUP\n",
	"NS1: $NS1\n",
	"NS2: $NS2\n";

	if ( -e $RESOLV_FILE ) {
		while ( -e $BACKUP ){
			rename $BACKUP, "${BACKUP}.$$"
		}
		rename $RESOLV_FILE, $BACKUP;
	}

	if ( ! open F, ">$RESOLV_FILE" ){
		print "Unable to create $RESOLV_FILE: $!";
		return 1;
	}

	print F "# resolv.conf generated by ppptool\n",
					"domain $DOMAIN\n",
					"search $DOMAIN\n",
					"nameserver $NS1\n",
					"nameserver $NS2\n";

	close F;

	return 0;
		
}

sub restore{

		if ( ! rename $BACKUP, $RESOLV_FILE ) {
			print "Error renaming $BACKUP file to $RESOLV_FILE\n";
			return 1;
		}
		return 0;
}

sub init{

	$RESOLV_FILE = "/tmp/resolv.conf";
	use File::Copy;
	use Getopt::Long;
	GetOptions( 
		"domain=s"  => \$DOMAIN,
		"backup=s"  => \$BACKUP,
		"ns1=s"  => \$NS1,
		"ns2=s"  => \$NS2,
		"create"  => \$CREATE_FLAG,
		"restore"  => \$RESTORE_FLAG,
	);

	if ( ! defined $BACKUP ) {
		print "Backup file option -backup is required\n"; 
		return 1;
	} elsif ( $BACKUP =~ /\s+/ ){
		print "Backup file name cannot contain spaces\n";
		return 1;
	} elsif ( $BACKUP !~ /^$RESOLV_FILE/ ){
		print "Backup file name must begin with $RESOLV_FILE\n";
		return 1;
	}

	return 0;
}

sub main{
	my $err = init;
	exit if $err != 0;
	$err = run;
	exit if $err != 0;
}

&main;
