/*
 * connectStatusUI.java
 *
 * Created on September 23, 2003, 3:50 PM
 */

/**
 *
 * @author  pdel
 */

import javax.swing.table.*;

public class connectStatusUI extends javax.swing.JFrame {
    
    /** Creates new form connectStatusUI */
    public connectStatusUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Network Connection", "OK"},
                {"LAN Connection", "OK"},
                {"ISP Connection", "OK"},
                {"VPN Connection", "DOWN"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 190));

        jPanel7.setMinimumSize(new java.awt.Dimension(266, 20));
        jPanel7.setPreferredSize(new java.awt.Dimension(266, 20));
        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Check Network Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNetworkStatus(evt);
            }
        });

        jPanel7.add(jButton2);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApp(evt);
            }
        });

        jPanel7.add(jButton1);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Help");
        jPanel7.add(jButton3);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("iWork Connection Status Tool");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel5, java.awt.BorderLayout.WEST);

        pack();
    }//GEN-END:initComponents

    private void checkNetworkStatus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNetworkStatus
        // Add your handling code here:
      
        TableModel tm = jTable1.getModel();
        for ( int i = 0; i<tm.getColumnCount(); i++ ){
            String ts = tm.getColumnName(i);
            System.out.println( "Column " + ts );
            for ( int j = 0 ; j<tm.getRowCount(); j++ ){
                Object val = tm.getValueAt(j,i);
                if ( val != null ) {
                    System.out.println( "Value: " + val );
                }
            }
           
        }
    }//GEN-LAST:event_checkNetworkStatus

    private void exitApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApp
        // Add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitApp
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new connectStatusUI().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
