/*
 * NetCheckUI.java
 *
 * Created on November 1, 2004, 5:06 PM
 */

/**
 *
 * @author  pdel
 */
public class NetCheckUI extends javax.swing.JFrame {
    
    /** Creates new form NetCheckUI */
    public NetCheckUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        InterfaceLabel = new javax.swing.JLabel();
        GatewayLabel = new javax.swing.JLabel();
        InternetLabel = new javax.swing.JLabel();
        SwanLabel = new javax.swing.JLabel();
        VPNLabel = new javax.swing.JLabel();
        InterfaceButton = new javax.swing.JButton();
        GatewayButton = new javax.swing.JButton();
        InternetButton = new javax.swing.JButton();
        SwanButton = new javax.swing.JButton();
        VPNButton = new javax.swing.JButton();
        ButtonPanel = new javax.swing.JPanel();
        ConnectionButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        PrefButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NetCheck");
        jLabel1.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(225, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(225, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(225, 25));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        CenterPanel.setLayout(new java.awt.GridBagLayout());

        CenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        InterfaceLabel.setText("Network Interface");
        InterfaceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(InterfaceLabel, gridBagConstraints);

        GatewayLabel.setText("Gateway");
        GatewayLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(GatewayLabel, gridBagConstraints);

        InternetLabel.setText("ISP/Internet Connection");
        InternetLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(InternetLabel, gridBagConstraints);

        SwanLabel.setText("SWAN Connection");
        SwanLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(SwanLabel, gridBagConstraints);

        VPNLabel.setText("VPN Gateway");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(VPNLabel, gridBagConstraints);

        InterfaceButton.setBackground(java.awt.Color.green);
        InterfaceButton.setText("Status: eth0 OK");
        InterfaceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InterfaceButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        InterfaceButton.setMaximumSize(new java.awt.Dimension(150, 25));
        InterfaceButton.setMinimumSize(new java.awt.Dimension(150, 25));
        InterfaceButton.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(InterfaceButton, gridBagConstraints);

        GatewayButton.setBackground(java.awt.Color.green);
        GatewayButton.setText("Status: 192.168.1.1 OK");
        GatewayButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GatewayButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        GatewayButton.setMaximumSize(new java.awt.Dimension(150, 25));
        GatewayButton.setMinimumSize(new java.awt.Dimension(150, 25));
        GatewayButton.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(GatewayButton, gridBagConstraints);

        InternetButton.setBackground(java.awt.Color.green);
        InternetButton.setText("Status: Internet OK");
        InternetButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InternetButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        InternetButton.setMaximumSize(new java.awt.Dimension(150, 25));
        InternetButton.setMinimumSize(new java.awt.Dimension(150, 25));
        InternetButton.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(InternetButton, gridBagConstraints);

        SwanButton.setBackground(java.awt.Color.yellow);
        SwanButton.setText("Status: No Connection");
        SwanButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SwanButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        SwanButton.setMaximumSize(new java.awt.Dimension(150, 25));
        SwanButton.setMinimumSize(new java.awt.Dimension(150, 25));
        SwanButton.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(SwanButton, gridBagConstraints);

        VPNButton.setBackground(java.awt.Color.green);
        VPNButton.setText("Status: ivpn-central OK");
        VPNButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VPNButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        VPNButton.setMaximumSize(new java.awt.Dimension(150, 25));
        VPNButton.setMinimumSize(new java.awt.Dimension(150, 25));
        VPNButton.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        CenterPanel.add(VPNButton, gridBagConstraints);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        ButtonPanel.setLayout(new java.awt.GridBagLayout());

        ButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConnectionButton.setText("Check Connection");
        ConnectionButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConnectionButton.setMargin(new java.awt.Insets(10, 10, 10, 10));
        ConnectionButton.setMaximumSize(new java.awt.Dimension(120, 25));
        ConnectionButton.setMinimumSize(new java.awt.Dimension(120, 25));
        ConnectionButton.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 3, 5);
        ButtonPanel.add(ConnectionButton, gridBagConstraints);

        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitButton.setMargin(new java.awt.Insets(10, 10, 10, 10));
        ExitButton.setMaximumSize(new java.awt.Dimension(120, 25));
        ExitButton.setMinimumSize(new java.awt.Dimension(120, 25));
        ExitButton.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        ButtonPanel.add(ExitButton, gridBagConstraints);

        PrefButton.setText("Preferences");
        PrefButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrefButton.setMargin(new java.awt.Insets(10, 10, 10, 10));
        PrefButton.setMaximumSize(new java.awt.Dimension(120, 25));
        PrefButton.setMinimumSize(new java.awt.Dimension(120, 25));
        PrefButton.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        ButtonPanel.add(PrefButton, gridBagConstraints);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel5, java.awt.BorderLayout.WEST);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NetCheckUI().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JButton ConnectionButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GatewayButton;
    private javax.swing.JLabel GatewayLabel;
    private javax.swing.JButton InterfaceButton;
    private javax.swing.JLabel InterfaceLabel;
    private javax.swing.JButton InternetButton;
    private javax.swing.JLabel InternetLabel;
    private javax.swing.JButton PrefButton;
    private javax.swing.JButton SwanButton;
    private javax.swing.JLabel SwanLabel;
    private javax.swing.JButton VPNButton;
    private javax.swing.JLabel VPNLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    
}
