/*
 * LogWindow.java
 *
 * Created on November 1, 2004, 4:55 PM
 */

/**
 *
 * @author  pdel
 */
import javax.swing.*;
import java.awt.*;

public class NetCheckLogWin extends javax.swing.JFrame {
    
    /** Creates new form LogWindow */
    public NetCheckLogWin() {
        initComponents();
    }
    
    public NetCheckLogWin(NetStatUI UI) {
        ui=UI;
        initComponents();
        setVisible(false);
        
   }
    public void clearText(){
        this.LogWindow.setText(null);
        repaint();
    }
    public void setCaret(){
        this.LogWindow.setCaretPosition( this.LogWindow.getText().length()  );
    }
    public void appendText( String t ){
        LogWindow.append(t);
        setCaret();
        repaint();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        statusPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LogWindow = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("NetCheck Log");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        statusPanel.setLayout(new java.awt.BorderLayout());

        statusPanel.setMinimumSize(new java.awt.Dimension(350, 200));
        statusPanel.setPreferredSize(new java.awt.Dimension(350, 200));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(550, 175));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 1000));
        LogWindow.setEditable(false);
        LogWindow.setMaximumSize(new java.awt.Dimension(100000, 100000));
        LogWindow.setMinimumSize(new java.awt.Dimension(550, 10000));
        LogWindow.setPreferredSize(new java.awt.Dimension(550, 5000));
        jScrollPane1.setViewportView(LogWindow);

        statusPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(statusPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        jButton1.setMnemonic('c');
        jButton1.setText("Close");
        jButton1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(55, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(55, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close(evt);
            }
        });

        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        jLabel1.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log");
        jLabel1.setPreferredSize(new java.awt.Dimension(55, 25));
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void Close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close
        // Add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Close
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NetCheckLogWin().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea LogWindow;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
    protected NetStatUI ui;
}
