/*
 * NetStatUI.java
 *
 * Created on January 6, 2004, 10:53 AM
 */

/**
 *
 * @author  Peter Delevoryas
 */

import java.awt.*;
import java.awt.event.*;
import java.awt.geom.*;
import javax.swing.*;
import java.util.*;
import java.net.*;
import java.io.*;

public class NetStatUI_2 extends javax.swing.JFrame {
    
    /** Creates new form NetStatUI */
    public NetStatUI_2() {
        initComponents();
        hideNetworkObjects();
        //this.setSize(650, 400);
    }
    
    public void hideNetworkObjects(){
        LocalHostButton.setVisible(false);
        LocalToGatewayLink.setVisible(false);
        GatewayButon.setVisible(false);
        GatewayToInternetLink.setVisible(false);
        InternetButton.setVisible(false);
        InternetToVpnLink.setVisible(false);
        VpnGatewayButton.setVisible(false);
        SwanButton.setVisible(false);
        displayPanel.remove(SwanButton);
        displayPanel.validate();
        
    }
    
    
    public void printToLog( String text ){
        String txt = ( text + "\n" );
        this.LogWindow.append(txt);
        
        this.LogWindow.setCaretPosition( this.LogWindow.getText().length()  );
        
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        SwanButton = new javax.swing.JButton();
        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        LocalHostButton = new javax.swing.JButton();
        LocalToGatewayLink = new javax.swing.JLabel();
        GatewayButon = new javax.swing.JButton();
        GatewayToInternetLink = new javax.swing.JLabel();
        InternetHostsPanel = new javax.swing.JPanel();
        InternetButton = new javax.swing.JButton();
        InternetToVpnLink = new javax.swing.JLabel();
        GatewayPanel = new javax.swing.JPanel();
        VpnGatewayButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LogWindow = new javax.swing.JTextArea();
        FooterPanel = new javax.swing.JPanel();
        Check = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RightFillerPanel = new javax.swing.JPanel();
        LeftFillerPanel = new javax.swing.JPanel();

        SwanButton.setBackground(new java.awt.Color(0, 255, 0));
        SwanButton.setText("SWAN");

        setTitle("iWork NetStat Utility");
        setBackground(new java.awt.Color(153, 153, 255));
        setFont(new java.awt.Font("Dialog", 1, 12));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        HeaderPanel.setLayout(new java.awt.BorderLayout());

        HeaderPanel.setMaximumSize(new java.awt.Dimension(150, 25));
        HeaderPanel.setMinimumSize(new java.awt.Dimension(150, 25));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(150, 25));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Network Status Utility");
        HeaderPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.NORTH);

        CenterPanel.setLayout(new java.awt.BorderLayout(10, 0));

        CenterPanel.setMinimumSize(new java.awt.Dimension(600, 250));
        CenterPanel.setPreferredSize(new java.awt.Dimension(600, 250));
        displayPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        displayPanel.setBorder(new javax.swing.border.EtchedBorder());
        displayPanel.setMinimumSize(new java.awt.Dimension(600, 50));
        displayPanel.setPreferredSize(new java.awt.Dimension(600, 50));
        LocalHostButton.setText("LocalHost");
        displayPanel.add(LocalHostButton);

        LocalToGatewayLink.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        LocalToGatewayLink.setPreferredSize(new java.awt.Dimension(60, 10));
        LocalToGatewayLink.setOpaque(true);
        displayPanel.add(LocalToGatewayLink);

        GatewayButon.setText("Gateway");
        displayPanel.add(GatewayButon);

        GatewayToInternetLink.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        GatewayToInternetLink.setPreferredSize(new java.awt.Dimension(60, 10));
        GatewayToInternetLink.setOpaque(true);
        displayPanel.add(GatewayToInternetLink);

        InternetHostsPanel.setLayout(new java.awt.GridLayout(1, 0));

        InternetButton.setText("Internet");
        InternetHostsPanel.add(InternetButton);

        displayPanel.add(InternetHostsPanel);

        InternetToVpnLink.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        InternetToVpnLink.setPreferredSize(new java.awt.Dimension(60, 10));
        InternetToVpnLink.setOpaque(true);
        displayPanel.add(InternetToVpnLink);

        VpnGatewayButton.setText("VPN Gateway");
        GatewayPanel.add(VpnGatewayButton);

        displayPanel.add(GatewayPanel);

        CenterPanel.add(displayPanel, java.awt.BorderLayout.NORTH);

        statusPanel.setLayout(new java.awt.BorderLayout());

        statusPanel.setMinimumSize(new java.awt.Dimension(550, 175));
        statusPanel.setPreferredSize(new java.awt.Dimension(550, 175));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(550, 175));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 1000));
        LogWindow.setEditable(false);
        LogWindow.setMaximumSize(new java.awt.Dimension(100000, 100000));
        LogWindow.setMinimumSize(new java.awt.Dimension(550, 10000));
        LogWindow.setPreferredSize(new java.awt.Dimension(550, 100000));
        jScrollPane1.setViewportView(LogWindow);

        statusPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        CenterPanel.add(statusPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        FooterPanel.setMaximumSize(new java.awt.Dimension(400, 40));
        FooterPanel.setMinimumSize(new java.awt.Dimension(400, 40));
        FooterPanel.setPreferredSize(new java.awt.Dimension(400, 40));
        Check.setText("Check Connection");
        Check.setMaximumSize(new java.awt.Dimension(150, 25));
        Check.setMinimumSize(new java.awt.Dimension(150, 25));
        Check.setPreferredSize(new java.awt.Dimension(150, 25));
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConnection(evt);
            }
        });

        FooterPanel.add(Check);

        Cancel.setText("Cancel");
        Cancel.setMaximumSize(new java.awt.Dimension(75, 25));
        Cancel.setMinimumSize(new java.awt.Dimension(75, 25));
        Cancel.setPreferredSize(new java.awt.Dimension(75, 25));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNetStat(evt);
            }
        });

        FooterPanel.add(Cancel);

        jButton4.setText("Exit");
        jButton4.setMaximumSize(new java.awt.Dimension(60, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(60, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitApp(evt);
            }
        });

        FooterPanel.add(jButton4);

        getContentPane().add(FooterPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(RightFillerPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(LeftFillerPanel, java.awt.BorderLayout.WEST);

        pack();
    }//GEN-END:initComponents
    
    private void cancelNetStat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNetStat
        // Add your handling code here:
        
        this.Cancel.setEnabled(false);
        
        
    }//GEN-LAST:event_cancelNetStat
    
    private void ExitApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitApp
        // Add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitApp
    private class Blink extends Thread {
        private Component c;
        boolean stopBlinking = false;
        private static final long sleepInterval = 1000;
        public Blink( Component C ){
            c=C;
        }
        
        public void stopBlinking(){
            c.setBackground(Color.green);
            c.repaint();
            stopBlinking = true;
        }
        public void run() {
            c.setBackground(Color.green);
            while ( true ){
                if ( stopBlinking == true ){
                    
                    return;
                }
                if ( c.getBackground() == Color.yellow ){
                    c.setBackground(Color.green);
                    //System.out.println( "green" );
                } else if (  c.getBackground() == Color.green ){
                    c.setBackground(Color.yellow);
                    // System.out.println( "yellow" );
                }
                c.repaint();
                try{
                    sleep(sleepInterval);
                    yield();
                }catch ( InterruptedException iex ) {
                    
                }
            }
        }
    }
    
    protected class NetStatThread extends Thread {
        
        private NetStatUI ui;
        private Blink LocalHostBlink;
        private Blink GatewayLinkBlink;
        private Blink GatewayBlink;
        private Blink InternetLinkBlink;
        private Blink InternetBlink;
        private Blink VpnLinkBlink;
        private Blink VpnGatewayBlink;
        private static final long sleepInterval = 5000;
        protected parseIPConfig IPConfig;
        protected Hashtable IPConfigInfo;
        protected Object LanInfoObject ;
        Hashtable LanInfo;
        protected final String DefaultVpnServer = "ivpn-central.sun.com";
        protected final int DefaultVpnPort = 80;
        
        public NetStatThread( NetStatUI UI ){
            ui=UI;
            LocalHostBlink = new Blink( ui.LocalHostButton );
            GatewayLinkBlink = new Blink( ui.LocalToGatewayLink );
            GatewayBlink = new Blink( ui.GatewayButon );
            InternetLinkBlink = new Blink( ui.GatewayToInternetLink );
            InternetBlink = new Blink( ui.InternetButton );
            VpnLinkBlink = new Blink( ui.InternetToVpnLink );
            VpnGatewayBlink = new Blink( ui.VpnGatewayButton );
            
            //start();
        }
        
        public void getIPConfig(){
            IPConfig = new parseIPConfig("/all");
            IPConfigInfo = IPConfig.getInfo();
            
            // an 'up' interface will have an IP # and a gateway
            
            // get IP address and gateway
            LanInfoObject = IPConfigInfo.get( HeadingFields.LanHeading );
            // contains Hashtable pointing to vector of items
            LanInfo = new Hashtable();
            if ( LanInfoObject instanceof Hashtable ){
                LanInfo = (Hashtable)LanInfoObject;
                if ( LanInfo.size() < 1 ){
                    JOptionPane.showMessageDialog(new JFrame(), "No information from IPConfig", "IP Config Error", JOptionPane.ERROR_MESSAGE );
                    ui.Check.setEnabled(false);
                    ui.Cancel.setEnabled(false);
                    
                }
            }
            
            
        }
        
        public void run() {
            //NetStat stat = new NetStat();
            
            ui.LocalHostButton.setVisible(true);
            
            LocalHostBlink.start();
            
            try{
                sleep( sleepInterval );
                yield();
            } catch ( InterruptedException iex ){
                
            }
            
            System.out.println( "Checking connection .." );
            ui.printToLog("Checking connection .." );
            
            //- First, verify that the user is not already connected to the VPN/SWAN
            /*
            if ( stat.checkConnection("one.central.sun.com") == true ){
                ui.LocalHostButton.setBackground(Color.green);
                ui.LocalToGatewayLink.setBackground(Color.green);
                ui.GatewayButon.setBackground(Color.green);
                ui.GatewayToInternetLink.setBackground(Color.green);
                ui.InternetButton.setBackground(Color.green);
                ui.InternetToVpnLink.setBackground(Color.green);
                ui.VpnGatewayButton.setBackground(Color.green);
                System.out.println( "Connection to SWAN OK" );
                ui.printToLog("Connection to SWAN OK" );
                LocalHostBlink.stopBlinking();
             **/
            
            if ( this.checkSwan() == true ){
                ui.LocalHostButton.setBackground(Color.green);
                ui.LocalToGatewayLink.setBackground(Color.green);
                ui.GatewayButon.setBackground(Color.green);
                ui.GatewayToInternetLink.setBackground(Color.green);
                ui.InternetButton.setBackground(Color.green);
                ui.InternetToVpnLink.setBackground(Color.green);
                ui.VpnGatewayButton.setBackground(Color.green);
                System.out.println( "Connection to SWAN OK" );
                ui.printToLog("Connection to SWAN OK" );
                LocalHostBlink.stopBlinking();
                //for ( int i=0; i<ui.displayPanel.getComponentCount(); i++ ){
                 //   ui.displayPanel.getComponent(i).setVisible(false);
                //}
                ui.hideNetworkObjects();
                ui.LocalHostButton.setVisible(true);
                ui.LocalToGatewayLink.setVisible(true);
                ui.SwanButton.setBackground(Color.green);
                ui.displayPanel.add(ui.SwanButton, 2);
                ui.SwanButton.setVisible(true);
                ui.displayPanel.repaint();
                
            }  else {
                
                System.out.println( "No Connection to SWAN, checking network configuration .." );
                ui.printToLog("No Connection to SWAN, checking network configuration .." );
                LocalHostBlink.stopBlinking();
                ui.LocalToGatewayLink.setVisible(true);
                GatewayLinkBlink.start();
                try{
                    sleep( sleepInterval );
                    yield();
                } catch ( InterruptedException iex ){
                    
                }
                
                
                
                getIPConfig();
                
                //"Media State . . . . . . . . . . . : Media disconnected" ??
                if ( LanInfo.containsKey( HeadingFields.MediaState ) ){
                    Vector MediaState = (Vector)LanInfo.get( HeadingFields.MediaState );
                    String state = MediaState.get(0).toString().trim();
                    if ( state.startsWith("Media disconnected") ){
                        System.out.println( "Network cable unplugged, check connections" );
                        GatewayLinkBlink.stopBlinking();
                        setColors(Color.red);
                        ui.printToLog("Network cable unplugged, check connections" );
                        return;
                    }
                }
                
                Vector IPAddress = (Vector)LanInfo.get( HeadingFields.IPAddress );
                Vector DefaultGW = (Vector)LanInfo.get( HeadingFields.DefaultGateway );
                Vector NetMask = (Vector)LanInfo.get( HeadingFields.SubnetMask );
                Vector DnsServers = (Vector)LanInfo.get( HeadingFields.DNSServers );
                
                String msg = new String(
                "\n" + "IP address: " + (String)IPAddress.get(0) + "\n" +
                "Default Gateway: " + (String)DefaultGW.get(0)  + "\n" +
                "Netmask: " + (String)NetMask.get(0) + "\n" );
                
                System.out.println( msg );
                ui.printToLog(msg);
                
                String DefaultGateway = (String)DefaultGW.get(0);
                //- Connectivity to their default router (DSL/cablemodem)?
                
                if ( this.checkGateway(DefaultGateway ) ){
                    
                    GatewayLinkBlink.stopBlinking();
                    ui.LocalToGatewayLink.setBackground(Color.green);
                    ui.GatewayButon.setVisible(true);
                    ui.GatewayButon.setBackground(Color.green);
                    
                    msg = ( "Connection to Default Gateway " + DefaultGateway + " OK" );
                    System.out.println( msg );
                    ui.printToLog(msg);
                    
                    // Check for host on network
                    ui.GatewayToInternetLink.setVisible(true);
                    InternetLinkBlink.start();
                    
                    try{
                        sleep( sleepInterval );
                        yield();
                    } catch ( InterruptedException iex ){
                        
                    }
                    
                    msg = ( "Checking Connection to Internet"  );
                    System.out.println( msg );
                    ui.printToLog(msg);
                    
                    if ( this.checkInternet() ){
                        msg = ( "Connection to Internet OK"  );
                        
                        
                        System.out.println( msg );
                        ui.printToLog(msg);
                        InternetLinkBlink.stopBlinking();
                        ui.GatewayToInternetLink.setBackground(Color.green);
                        ui.InternetButton.setVisible(true);
                        ui.InternetButton.setBackground(Color.green);
                        ui.displayPanel.repaint();
                    } else {
                        
                        msg = ( "No Connection to Internet"  );
                        System.out.println( msg );
                        ui.printToLog(msg);
                        InternetLinkBlink.stopBlinking();
                        ui.GatewayToInternetLink.setBackground(Color.red);
                        ui.InternetButton.setVisible(true);
                        ui.InternetButton.setBackground(Color.red);
                        ui.displayPanel.repaint();
                        return;
                    }
                    
                /*
                System.out.println( "Checking ISP connection .. pinging DNS server" );
                if ( stat.Host.isAlive( (String)DnsServers.get(0) ) ){
                    System.out.println( "Ping of ISP DNS server: " + (String)DnsServers.get(0) + " is alive" );
                 
                } else {
                    System.out.println( "Ping of ISP DNS server: " + (String)DnsServers.get(0) + " not responding or host not found" );
                }
                 **/
                    ui.InternetToVpnLink.setVisible(true);
                    VpnLinkBlink.start();
                    //VpnGatewayBlink
                    
                    msg = ( "Checking Connection to vpn server " + DefaultVpnServer );
                    System.out.println( msg );
                    ui.printToLog(msg);
                    
                    
                    
                    boolean connectOk = false;
                    try {
                        Socket vpnSocket = new Socket( DefaultVpnServer, DefaultVpnPort );
                        
                        try{
                            sleep( sleepInterval );
                            yield();
                        } catch ( InterruptedException iex ){
                            
                        }
                        VpnLinkBlink.stopBlinking();
                        ui.InternetToVpnLink.setBackground(Color.green);
                        ui.VpnGatewayButton.setVisible(true);
                        ui.VpnGatewayButton.setBackground(Color.green);
                        ui.displayPanel.repaint();
                        msg = ( "Connectivity to " + DefaultVpnServer + " OK" );
                        System.out.println( msg );
                        ui.printToLog(msg);
                        
                        connectOk = true;
                        vpnSocket.close();
                    } catch ( UnknownHostException uh  ){
                        msg = ( "No connection to " + DefaultVpnServer + ": Host Unknown" );
                        System.out.println(msg);
                        ui.printToLog(msg);
                        ui.InternetToVpnLink.setBackground(Color.red);
                        ui.VpnGatewayButton.setVisible(true);
                        ui.VpnGatewayButton.setBackground(Color.red);
                        //uh.printStackTrace();
                        System.out.println( uh.getLocalizedMessage() );
                    } catch ( IOException iox ){
                        if ( connectOk == false ){
                            msg = ( "No connection to " + DefaultVpnServer  + ": IO Exception" );
                            System.out.println(msg);
                            System.out.println( iox.getLocalizedMessage() );
                            ui.InternetToVpnLink.setBackground(Color.red);
                            ui.VpnGatewayButton.setVisible(true);
                            ui.VpnGatewayButton.setBackground(Color.red);
                            //iox.printStackTrace();
                        }
                    }
                    
                    
                    
                    
                    return;
                } else {
                    ui.LocalToGatewayLink.setVisible(true);
                    ui.LocalToGatewayLink.setBackground(Color.red);
                    ui.GatewayButon.setVisible(true);
                    ui.GatewayButon.setBackground(Color.red);
                    msg = ( "No Connection to Default Gateway " + DefaultGateway + "\n" +
                    "Check connection to Default Gateway" +  "Netmask: " + (String)NetMask.get(0) );
                    System.out.println(msg);
                    ui.printToLog(msg);
                }
                
                
            }
            
            
        }
        private boolean checkInternet(){
            // ping or socket connect to hosts
            return true;
        }
        private boolean checkVpn(){
            // socket 80 vpn gateways
            
            String DefaultVpnServer = "Xivpn-central.sun.com";
            int DefaultVpnPort = 80;
            return true;
        }
        
        private boolean checkSwan(){
            
            // ping set of machines
            // url connect to sunweb.<domain>
            WinPing swanHost = new WinPing();
            return swanHost.isAlive("sunweb.central.sun.com");
            
        }
        private boolean checkGateway(String gw){
            WinPing host = new WinPing();
            if ( host.isAlive(gw) )return true;
            return false;
        }
        private boolean checkLocalHost(){
            
            return true;
            
        }
        private boolean checkConnection( String type ){
            
            return true;
        }
        
        
    }
    
    private void setColors( Color c ){
        this.LocalHostButton.setBackground(c);
        this.LocalToGatewayLink.setBackground(c);
        this.GatewayButon.setBackground(c);
        this.GatewayToInternetLink.setBackground(c);
        this.InternetButton.setBackground(c);
        this.InternetToVpnLink.setBackground(c);
        this.VpnGatewayButton.setBackground(c);
        
    }
    
    private void checkConnection(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConnection
        // Add your handling code here:
        hideNetworkObjects();
        LogWindow.setText(null);
        setColors( Color.lightGray );
        this.LocalHostButton.setBackground(Color.green);
        this.Cancel.setEnabled(true);
        
        NetStatT = new NetStatThread(this);
        NetStatT.start();
        
    }//GEN-LAST:event_checkConnection
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NetStatUI().show();
    }
    
    public void drawImages() {
        // create graphic images of host, gateway, vpn server
        //Graphics2D g2d = (Graphics2d) g;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Cancel;
    protected javax.swing.JPanel CenterPanel;
    protected javax.swing.JButton Check;
    protected javax.swing.JPanel FooterPanel;
    protected javax.swing.JButton GatewayButon;
    protected javax.swing.JPanel GatewayPanel;
    protected javax.swing.JLabel GatewayToInternetLink;
    protected javax.swing.JPanel HeaderPanel;
    protected javax.swing.JButton InternetButton;
    protected javax.swing.JPanel InternetHostsPanel;
    protected javax.swing.JLabel InternetToVpnLink;
    protected javax.swing.JPanel LeftFillerPanel;
    protected javax.swing.JButton LocalHostButton;
    protected javax.swing.JLabel LocalToGatewayLink;
    protected javax.swing.JTextArea LogWindow;
    protected javax.swing.JPanel RightFillerPanel;
    protected javax.swing.JButton SwanButton;
    protected javax.swing.JButton VpnGatewayButton;
    protected javax.swing.JPanel displayPanel;
    protected javax.swing.JButton jButton4;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
    protected NetStatThread NetStatT;
   
}
