/*
 * LogWindow.java
 *
 * Created on December 1, 2003, 1:53 PM
 */

/**
 *
 * @author  pdel
 */

import javax.swing.*;
import java.awt.*;
import java.io.*;

public class NetStatHelpWin extends javax.swing.JFrame {
    
    private NetStatUI ui;
    
    /** Creates new form LogWindow */
    public NetStatHelpWin() {
        initComponents();
        loadHelp();
    }
    
    public NetStatHelpWin(NetStatUI UI) {
        ui=UI;
        initComponents();
        this.setIconImage( ui.getMinimizeImage() );
        loadHelp();
    }
    public void showWin(){
       
        this.setVisible(true);
        //this.requestFocus();
    }
    
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.BorderLayout(10, 0));

        setTitle("NetCheck Help");
        setBackground(new java.awt.Color(196, 196, 224));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        headerPanel.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        headerPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        headerPanel.setPreferredSize(new java.awt.Dimension(130, 30));
        jLabel1.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Help");
        jLabel1.setMaximumSize(new java.awt.Dimension(85, 18));
        jLabel1.setMinimumSize(new java.awt.Dimension(85, 18));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 20));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(jLabel1);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        CenterPanel.setLayout(new java.awt.BorderLayout(20, 0));

        CenterPanel.setBackground(new java.awt.Color(196, 196, 224));
        CenterPanel.setPreferredSize(new java.awt.Dimension(650, 450));
        jScrollPane1.setBackground(new java.awt.Color(196, 196, 224));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 150));
        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        CenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        ButtonPanel.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Desktop.background"));
        ButtonPanel.setMaximumSize(new java.awt.Dimension(80, 35));
        jButton1.setBackground(new java.awt.Color(196, 196, 224));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11));
        jButton1.setMnemonic('c');
        jButton1.setText("Close");
        jButton1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(75, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeWin(evt);
            }
        });

        ButtonPanel.add(jButton1);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    private void closeWin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWin
        // Add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeWin
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.setVisible( false );
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NetStatHelpWin().show();
    }
    
    public void scrollLogWin() {
        
        this.jTextPane1.setCaretPosition(jTextPane1.getText().length());
        /*
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        JViewport jv = jScrollPane1.getViewport();
         
        JScrollBar js = jScrollPane1.getVerticalScrollBar();
        int incr = js.getUnitIncrement();
         
         
        Point vp = jv.getViewPosition();
        int rowHeight = this.jTextPane1.getGraphics().getFontMetrics().getHeight();
        //int rowWidth = this.LogWin.getWidth();
        vp.y += rowHeight * 2 ;
        vp.x = 0;
         
        jv.setViewPosition(vp );
         
         
        //LogWin.scrollRectToVisible(LogWin.getBounds());
         
        //this.LogWin.revalidate();
        //this.repaint();
         
        //this.jTextPane1.repaint();
        //this.jTabbedPane1.repaint();
        //this.jTabbedPane1.getParent().repaint();
        //this.repaint();
         **/
        
        this.invalidate();
    }
    
    public void loadHelp() {
        java.net.URL helpURL = getClass().getResource(HelpUrl);
        if (helpURL != null) {
            try {
                jTextPane1.setPage(helpURL);
                
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: " + HelpUrl );
        }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel ButtonPanel;
    protected javax.swing.JPanel CenterPanel;
    protected javax.swing.JPanel headerPanel;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    protected final String HelpUrl = "NetCheckHelp.html";
}
