/*
 * VPN3K/vpn3kSimple.java
 *
 * Created on December 4, 2003, 8:59 PM
 */

/**
 *
 * @author  pdel
 */
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;

public class vpn3kSimple extends javax.swing.JFrame {
    
    /** Creates new form vpn3kSimple */
    public vpn3kSimple() {
        initComponents();
        this.pack();
    }
    
    public vpn3kSimple(vpn3k GUI) {
        UI=GUI;
        setIconImage(UI.minimizeIcon.getImage());
        initComponents();
        this.pack();
        loadAccounts();
        initUIMenu();
    }
    
   
    protected void loadAccounts(){
        //String[] acctNames = (String[])accts.keySet().toArray();
        DefaultTableModel tm = (DefaultTableModel)UI.jTable1.getModel();
        // zero out AccountCombo
        int items = AccountCombo.getItemCount();
        
        // dc.removeAllElements();
        AccountCombo.setModel(new DefaultComboBoxModel());
        DefaultComboBoxModel dc = (DefaultComboBoxModel)AccountCombo.getModel();
        
        for ( int i=0; i < tm.getRowCount(); i++ ){
            String name = (String) tm.getValueAt(i,  0 );
            //AccountCombo.insertItemAt(name,  i );
            dc.insertElementAt(name,i);
            
        }
        AccountCombo.setModel(dc);
        AccountCombo.setSelectedIndex(UI.getSelectedAccountRow());
    }
    private void initUIMenu(){
        
        
        menuConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println( "connect via simple" );
                ConnectButton.setText("Disconnect");
                
                // get selected account name
                
                UI.menuConnect(evt);
                
            }
        });
        
        menuDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println( "disconnect via simple" );
                ConnectButton.setText("Connect");
                UI.menuDisconnect(evt);
                
            }
        });
        
        
        
        menuSetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println( "set default via simple" );
                int currentIndex = AccountCombo.getSelectedIndex();
                String selectedAccount = (String)AccountCombo.getSelectedItem();
                DefaultTableModel tm = (DefaultTableModel)UI.jTable1.getModel();
                UI.jTable1.setRowSelectionInterval(currentIndex, currentIndex );
                UI.setDefaultAccount(evt);
                loadAccounts();
            }
        });
        
        //menuImport
        
        //menuExit
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println( "exit via simple" );
                UI.exitApp(evt);
            }
        });
        
        //StatusMenu
        //menuStatistics
        menuStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UI.showStatsWindow(evt);
                
            }
        });
        
        //menuNotifications
        menuNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UI.showNotifications(evt);
                
            }
        });
        
        //menuResetStats
        //OptionsMenu
        
        //menuPreferences
        
        //HelpMenu
        //menuAbout
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UI.menuAbout(evt);
                
            }
        });
        //menuHelp
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UI.showHelp(evt);
                
            }
        });
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        AccountCombo = new javax.swing.JComboBox();
        ConnectButton = new javax.swing.JButton();
        LogoLabel = new javax.swing.JLabel();
        StatusField = new javax.swing.JLabel();
        ProgressPanel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        EntryMenu = new javax.swing.JMenu();
        menuConnect = new javax.swing.JMenuItem();
        menuDisconnect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuImport = new javax.swing.JMenuItem();
        menuSetDefault = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        menuExit = new javax.swing.JMenuItem();
        StatusMenu = new javax.swing.JMenu();
        menuStatistics = new javax.swing.JMenuItem();
        menuNotifications = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        menuResetStats = new javax.swing.JMenuItem();
        OptionsMenu = new javax.swing.JMenu();
        menuAdvancedMode = new javax.swing.JMenuItem();
        menuPreferences = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenuItem();

        setTitle("ITvpntool VPN 3000 Client | Simple Mode");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(190, 190, 226));
        jPanel1.setMaximumSize(new java.awt.Dimension(575, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(575, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(575, 100));
        AccountCombo.setBackground(new java.awt.Color(190, 190, 226));
        AccountCombo.setMaximumSize(new java.awt.Dimension(250, 25));
        AccountCombo.setMinimumSize(new java.awt.Dimension(250, 25));
        AccountCombo.setPreferredSize(new java.awt.Dimension(250, 25));
        AccountCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSelectedAccount(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(AccountCombo, gridBagConstraints);

        ConnectButton.setBackground(new java.awt.Color(190, 190, 226));
        ConnectButton.setFont(new java.awt.Font("Dialog", 1, 11));
        ConnectButton.setMnemonic('e');
        ConnectButton.setText("Connect");
        ConnectButton.setMaximumSize(new java.awt.Dimension(125, 25));
        ConnectButton.setMinimumSize(new java.awt.Dimension(125, 25));
        ConnectButton.setPreferredSize(new java.awt.Dimension(125, 25));
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 20, 5);
        jPanel1.add(ConnectButton, gridBagConstraints);

        LogoLabel.setBackground(new java.awt.Color(190, 190, 226));
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iWork_enabled.png")));
        LogoLabel.setMaximumSize(new java.awt.Dimension(150, 65));
        LogoLabel.setMinimumSize(new java.awt.Dimension(150, 65));
        LogoLabel.setPreferredSize(new java.awt.Dimension(150, 65));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 5);
        jPanel1.add(LogoLabel, gridBagConstraints);

        StatusField.setBackground(new java.awt.Color(190, 190, 226));
        StatusField.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusField.setMaximumSize(new java.awt.Dimension(350, 25));
        StatusField.setMinimumSize(new java.awt.Dimension(350, 25));
        StatusField.setPreferredSize(new java.awt.Dimension(350, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(StatusField, gridBagConstraints);

        ProgressPanel.setBackground(new java.awt.Color(190, 190, 226));
        ProgressPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        jPanel1.add(ProgressPanel, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        EntryMenu.setBackground(new java.awt.Color(255, 255, 255));
        EntryMenu.setMnemonic('C');
        EntryMenu.setText("Connection Entries");
        EntryMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        menuConnect.setFont(new java.awt.Font("Dialog", 0, 12));
        menuConnect.setMnemonic('C');
        menuConnect.setText("Connect");
        menuConnect.setToolTipText("Connect");
        EntryMenu.add(menuConnect);

        menuDisconnect.setFont(new java.awt.Font("Dialog", 0, 12));
        menuDisconnect.setMnemonic('D');
        menuDisconnect.setText("Disconnect");
        EntryMenu.add(menuDisconnect);

        EntryMenu.add(jSeparator1);

        menuImport.setFont(new java.awt.Font("Dialog", 0, 12));
        menuImport.setMnemonic('I');
        menuImport.setText("Import...");
        menuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportProfile(evt);
            }
        });

        EntryMenu.add(menuImport);

        menuSetDefault.setFont(new java.awt.Font("Dialog", 0, 12));
        menuSetDefault.setMnemonic('S');
        menuSetDefault.setText("Set as Default Connection Entry");
        EntryMenu.add(menuSetDefault);

        EntryMenu.add(jSeparator5);

        menuExit.setFont(new java.awt.Font("Dialog", 0, 12));
        menuExit.setMnemonic('X');
        menuExit.setText("Exit VPN Client");
        EntryMenu.add(menuExit);

        jMenuBar2.add(EntryMenu);

        StatusMenu.setBackground(new java.awt.Color(255, 255, 255));
        StatusMenu.setMnemonic('S');
        StatusMenu.setText("Status");
        StatusMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        menuStatistics.setFont(new java.awt.Font("Dialog", 0, 12));
        menuStatistics.setText("Statistics");
        StatusMenu.add(menuStatistics);

        menuNotifications.setFont(new java.awt.Font("Dialog", 0, 12));
        menuNotifications.setText("Notifications");
        StatusMenu.add(menuNotifications);

        StatusMenu.add(jSeparator6);

        menuResetStats.setFont(new java.awt.Font("Dialog", 0, 12));
        menuResetStats.setText("Reset Stats");
        menuResetStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetStats(evt);
            }
        });

        StatusMenu.add(menuResetStats);

        jMenuBar2.add(StatusMenu);

        OptionsMenu.setBackground(new java.awt.Color(255, 255, 255));
        OptionsMenu.setMnemonic('O');
        OptionsMenu.setText("Options");
        OptionsMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        menuAdvancedMode.setFont(new java.awt.Font("Dialog", 0, 12));
        menuAdvancedMode.setMnemonic('a');
        menuAdvancedMode.setText("Advanced Mode");
        menuAdvancedMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedMode(evt);
            }
        });

        OptionsMenu.add(menuAdvancedMode);

        menuPreferences.setFont(new java.awt.Font("Dialog", 0, 12));
        menuPreferences.setText("Preferences...");
        menuPreferences.setEnabled(false);
        OptionsMenu.add(menuPreferences);

        jMenuBar2.add(OptionsMenu);

        HelpMenu.setBackground(new java.awt.Color(255, 255, 255));
        HelpMenu.setMnemonic('H');
        HelpMenu.setText("Help");
        HelpMenu.setFont(new java.awt.Font("Dialog", 0, 12));
        menuAbout.setFont(new java.awt.Font("Dialog", 0, 12));
        menuAbout.setMnemonic('A');
        menuAbout.setText("About ..");
        HelpMenu.add(menuAbout);

        menuHelp.setFont(new java.awt.Font("Dialog", 0, 12));
        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");
        HelpMenu.add(menuHelp);

        jMenuBar2.add(HelpMenu);

        setJMenuBar(jMenuBar2);

    }//GEN-END:initComponents

    private void menuImportProfile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportProfile
        // Add your handling code here:
        new ImportProfile( this.UI );
        loadAccounts();
    }//GEN-LAST:event_menuImportProfile

    private void resetStats(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetStats
        // Add your handling code here:
        this.UI.StatWindow.resetStats(evt);
        

    }//GEN-LAST:event_resetStats

    private void connectButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonClicked
        // Add your handling code here:
        
            UI.ConnectButtonActionPerformed(evt);
        
    }//GEN-LAST:event_connectButtonClicked

    private void setSelectedAccount(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSelectedAccount
        // Add your handling code here:
        
        int index = AccountCombo.getSelectedIndex();
        if ( index < 0 && AccountCombo.getItemCount() < 1 ){
           
           return;
        } else if ( index < 0 && AccountCombo.getItemCount() > 0 ){
            AccountCombo.setSelectedIndex(0);
            index = 0;
        }
        String selectedAcct = (String)AccountCombo.getSelectedItem();
        // set selected acct in vpn3k UI
        DefaultTableModel tm = (DefaultTableModel)UI.jTable1.getModel();
        int jtableRows = tm.getRowCount();
        if ( jtableRows < 0 ) return;
        if ( index > ( jtableRows - 1 ) ) return;
        UI.jTable1.setRowSelectionInterval(index,index);
        UI.setAccountButtons();
        // trying to find something for mercury bug
        this.getContentPane().repaint();
        
        //AccountCombo.setSelectedIndex(index);
        
    }//GEN-LAST:event_setSelectedAccount

    private void advancedMode(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedMode
        // Add your handling code here:
         if ( this.isVisible() == true ) {
             this.setVisible(false);
            this.hide();
        }
        if ( this.UI.isVisible() == false ){
            this.UI.StartupMode = 1;
            this.UI.setLocation(this.getLocation());
            this.UI.setVisible(true);
            this.UI.show();
            this.UI.repaint();
        }
        this.UI.setStartupMode();
    }//GEN-LAST:event_advancedMode
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       if ( this.isVisible() == true ) {
             this.setVisible(false);
            this.hide();
        }
    }//GEN-LAST:event_exitForm
    public javax.swing.JPanel getProgressPanel(){
        return ProgressPanel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new vpn3kSimple().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox AccountCombo;
    protected javax.swing.JButton ConnectButton;
    protected javax.swing.JMenu EntryMenu;
    protected javax.swing.JMenu HelpMenu;
    protected javax.swing.JLabel LogoLabel;
    protected javax.swing.JMenu OptionsMenu;
    protected javax.swing.JPanel ProgressPanel;
    protected javax.swing.JLabel StatusField;
    protected javax.swing.JMenu StatusMenu;
    protected javax.swing.JMenuBar jMenuBar2;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JSeparator jSeparator1;
    protected javax.swing.JSeparator jSeparator5;
    protected javax.swing.JSeparator jSeparator6;
    protected javax.swing.JMenuItem menuAbout;
    protected javax.swing.JMenuItem menuAdvancedMode;
    protected javax.swing.JMenuItem menuConnect;
    protected javax.swing.JMenuItem menuDisconnect;
    protected javax.swing.JMenuItem menuExit;
    protected javax.swing.JMenuItem menuHelp;
    protected javax.swing.JMenuItem menuImport;
    protected javax.swing.JMenuItem menuNotifications;
    protected javax.swing.JMenuItem menuPreferences;
    protected javax.swing.JMenuItem menuResetStats;
    protected javax.swing.JMenuItem menuSetDefault;
    protected javax.swing.JMenuItem menuStatistics;
    // End of variables declaration//GEN-END:variables
    protected vpn3k UI;
}
