/*
 * NewAccount.java
 *
 * Created on November 4, 2003, 3:08 PM
 */

/**
 *
 * @author  pdel
 */
public class VpnAccount_backup extends javax.swing.JDialog {
    
    /** Creates new form NewAccount */
    public VpnAccount_backup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public VpnAccount_backup(vpn3k vpnUI) {
        super( new JFrame(), true );
        UI = vpnUI;
        initComponents();
        show();
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        AuthButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        EntryPanel = new javax.swing.JPanel();
        AcctLabel = new javax.swing.JLabel();
        AcctName = new javax.swing.JTextField();
        DescriptionPanel = new javax.swing.JPanel();
        DescrLabel = new javax.swing.JLabel();
        DescrField = new javax.swing.JTextField();
        HostPanel = new javax.swing.JPanel();
        HostLabel = new javax.swing.JLabel();
        HostField = new javax.swing.JTextField();
        IconPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AuthTab = new javax.swing.JPanel();
        GroupAuthPanel = new javax.swing.JPanel();
        GroupAuthButtonPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        GroupNamePanel = new javax.swing.JPanel();
        AcctLabel1 = new javax.swing.JLabel();
        AcctName1 = new javax.swing.JTextField();
        GroupPasswdPanel = new javax.swing.JPanel();
        DescrLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        GroupConfirmPassPanel = new javax.swing.JPanel();
        HostLabel1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        GroupCertPanel = new javax.swing.JPanel();
        GroupAuthButtonPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        GroupCertNamePanel = new javax.swing.JPanel();
        CertNameLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        CertChainPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        TransportTab = new javax.swing.JPanel();
        BackupServerTab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("VPN Client | Create New VPN Connection Entry");
        setBackground(new java.awt.Color(190, 190, 226));
        setForeground(java.awt.Color.blue);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(190, 190, 226));
        EntryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        EntryPanel.setBackground(new java.awt.Color(190, 190, 226));
        EntryPanel.setMaximumSize(new java.awt.Dimension(325, 30));
        EntryPanel.setMinimumSize(new java.awt.Dimension(325, 30));
        EntryPanel.setPreferredSize(new java.awt.Dimension(325, 30));
        AcctLabel.setDisplayedMnemonic('C');
        AcctLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        AcctLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AcctLabel.setText(" Connection Entry:  ");
        AcctLabel.setPreferredSize(new java.awt.Dimension(115, 15));
        EntryPanel.add(AcctLabel);

        AcctName.setMaximumSize(new java.awt.Dimension(200, 20));
        AcctName.setMinimumSize(new java.awt.Dimension(200, 20));
        AcctName.setPreferredSize(new java.awt.Dimension(200, 20));
        EntryPanel.add(AcctName);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(EntryPanel, gridBagConstraints);

        DescriptionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        DescriptionPanel.setBackground(new java.awt.Color(190, 190, 226));
        DescriptionPanel.setMaximumSize(new java.awt.Dimension(325, 30));
        DescriptionPanel.setMinimumSize(new java.awt.Dimension(325, 30));
        DescriptionPanel.setPreferredSize(new java.awt.Dimension(325, 30));
        DescrLabel.setDisplayedMnemonic('D');
        DescrLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        DescrLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DescrLabel.setText("Description: ");
        DescrLabel.setPreferredSize(new java.awt.Dimension(115, 15));
        DescriptionPanel.add(DescrLabel);

        DescrField.setMaximumSize(new java.awt.Dimension(200, 20));
        DescrField.setMinimumSize(new java.awt.Dimension(200, 20));
        DescrField.setPreferredSize(new java.awt.Dimension(200, 20));
        DescriptionPanel.add(DescrField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(DescriptionPanel, gridBagConstraints);

        HostPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        HostPanel.setBackground(new java.awt.Color(190, 190, 226));
        HostPanel.setMaximumSize(new java.awt.Dimension(325, 30));
        HostPanel.setMinimumSize(new java.awt.Dimension(325, 30));
        HostPanel.setPreferredSize(new java.awt.Dimension(325, 30));
        HostLabel.setDisplayedMnemonic('H');
        HostLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        HostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HostLabel.setText("Host: ");
        HostLabel.setPreferredSize(new java.awt.Dimension(115, 15));
        HostLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HostPanel.add(HostLabel);

        HostField.setMaximumSize(new java.awt.Dimension(200, 20));
        HostField.setMinimumSize(new java.awt.Dimension(200, 20));
        HostField.setPreferredSize(new java.awt.Dimension(200, 20));
        HostPanel.add(HostField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(HostPanel, gridBagConstraints);

        IconPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IconPanel.setBackground(new java.awt.Color(190, 190, 226));
        IconPanel.setMaximumSize(new java.awt.Dimension(135, 60));
        IconPanel.setMinimumSize(new java.awt.Dimension(135, 60));
        IconPanel.setPreferredSize(new java.awt.Dimension(135, 60));
        jLabel4.setBackground(new java.awt.Color(190, 190, 226));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iWork_enabled.png")));
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 50));
        IconPanel.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(IconPanel, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(190, 190, 226));
        jTabbedPane1.setBackground(new java.awt.Color(190, 190, 226));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 12));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(175, 75));
        AuthTab.setLayout(new java.awt.GridBagLayout());

        AuthTab.setBackground(new java.awt.Color(190, 190, 226));
        AuthTab.setMaximumSize(new java.awt.Dimension(0, 0));
        AuthTab.setMinimumSize(new java.awt.Dimension(0, 0));
        AuthTab.setPreferredSize(new java.awt.Dimension(0, 200));
        GroupAuthPanel.setLayout(new java.awt.GridBagLayout());

        GroupAuthPanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupAuthButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        GroupAuthButtonPanel.setBackground(new java.awt.Color(190, 190, 226));
        jRadioButton1.setBackground(new java.awt.Color(190, 190, 226));
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 12));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Group Authentication");
        GroupAuthButtonPanel.add(jRadioButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        GroupAuthPanel.add(GroupAuthButtonPanel, gridBagConstraints);

        GroupNamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        GroupNamePanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupNamePanel.setMaximumSize(new java.awt.Dimension(425, 30));
        GroupNamePanel.setMinimumSize(new java.awt.Dimension(425, 30));
        GroupNamePanel.setPreferredSize(new java.awt.Dimension(425, 30));
        AcctLabel1.setDisplayedMnemonic('C');
        AcctLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        AcctLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AcctLabel1.setText("Group Name: ");
        AcctLabel1.setPreferredSize(new java.awt.Dimension(115, 15));
        GroupNamePanel.add(AcctLabel1);

        AcctName1.setEditable(false);
        AcctName1.setText("VPN nextGen");
        AcctName1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        AcctName1.setMaximumSize(new java.awt.Dimension(300, 20));
        AcctName1.setMinimumSize(new java.awt.Dimension(300, 20));
        AcctName1.setPreferredSize(new java.awt.Dimension(300, 20));
        GroupNamePanel.add(AcctName1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        GroupAuthPanel.add(GroupNamePanel, gridBagConstraints);

        GroupPasswdPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        GroupPasswdPanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupPasswdPanel.setMaximumSize(new java.awt.Dimension(425, 30));
        GroupPasswdPanel.setMinimumSize(new java.awt.Dimension(425, 30));
        GroupPasswdPanel.setPreferredSize(new java.awt.Dimension(425, 30));
        DescrLabel1.setDisplayedMnemonic('D');
        DescrLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        DescrLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DescrLabel1.setText("Password: ");
        DescrLabel1.setPreferredSize(new java.awt.Dimension(115, 15));
        GroupPasswdPanel.add(DescrLabel1);

        jPasswordField1.setEditable(false);
        jPasswordField1.setText("vpn4sun");
        jPasswordField1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPasswordField1.setMaximumSize(new java.awt.Dimension(300, 20));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(300, 20));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(300, 20));
        GroupPasswdPanel.add(jPasswordField1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        GroupAuthPanel.add(GroupPasswdPanel, gridBagConstraints);

        GroupConfirmPassPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        GroupConfirmPassPanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupConfirmPassPanel.setMaximumSize(new java.awt.Dimension(425, 30));
        GroupConfirmPassPanel.setMinimumSize(new java.awt.Dimension(425, 30));
        GroupConfirmPassPanel.setPreferredSize(new java.awt.Dimension(425, 30));
        HostLabel1.setDisplayedMnemonic('H');
        HostLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        HostLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HostLabel1.setText("Confirm Password: ");
        HostLabel1.setPreferredSize(new java.awt.Dimension(115, 15));
        HostLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        GroupConfirmPassPanel.add(HostLabel1);

        jPasswordField2.setEditable(false);
        jPasswordField2.setText("vpn4sun");
        jPasswordField2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPasswordField2.setMaximumSize(new java.awt.Dimension(300, 20));
        jPasswordField2.setMinimumSize(new java.awt.Dimension(300, 20));
        jPasswordField2.setPreferredSize(new java.awt.Dimension(300, 20));
        GroupConfirmPassPanel.add(jPasswordField2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        GroupAuthPanel.add(GroupConfirmPassPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        AuthTab.add(GroupAuthPanel, gridBagConstraints);

        GroupCertPanel.setLayout(new java.awt.GridBagLayout());

        GroupCertPanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupAuthButtonPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        GroupAuthButtonPanel1.setBackground(new java.awt.Color(190, 190, 226));
        jRadioButton2.setBackground(new java.awt.Color(190, 190, 226));
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 12));
        jRadioButton2.setText("Certificate Authentication");
        jRadioButton2.setEnabled(false);
        GroupAuthButtonPanel1.add(jRadioButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        GroupCertPanel.add(GroupAuthButtonPanel1, gridBagConstraints);

        GroupCertNamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        GroupCertNamePanel.setBackground(new java.awt.Color(190, 190, 226));
        GroupCertNamePanel.setMaximumSize(new java.awt.Dimension(325, 20));
        GroupCertNamePanel.setMinimumSize(new java.awt.Dimension(325, 20));
        GroupCertNamePanel.setPreferredSize(new java.awt.Dimension(325, 20));
        CertNameLabel.setDisplayedMnemonic('C');
        CertNameLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        CertNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CertNameLabel.setText("Name: ");
        CertNameLabel.setMaximumSize(new java.awt.Dimension(50, 15));
        CertNameLabel.setMinimumSize(new java.awt.Dimension(50, 15));
        CertNameLabel.setPreferredSize(new java.awt.Dimension(50, 15));
        GroupCertNamePanel.add(CertNameLabel);

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 12));
        jComboBox1.setMaximumSize(new java.awt.Dimension(200, 20));
        jComboBox1.setMinimumSize(new java.awt.Dimension(200, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(200, 20));
        jComboBox1.setEnabled(false);
        GroupCertNamePanel.add(jComboBox1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        GroupCertPanel.add(GroupCertNamePanel, gridBagConstraints);

        CertChainPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        CertChainPanel.setBackground(new java.awt.Color(190, 190, 226));
        CertChainPanel.setMaximumSize(new java.awt.Dimension(325, 20));
        CertChainPanel.setMinimumSize(new java.awt.Dimension(325, 20));
        CertChainPanel.setPreferredSize(new java.awt.Dimension(325, 20));
        jCheckBox1.setBackground(new java.awt.Color(190, 190, 226));
        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12));
        jCheckBox1.setText("Send CA Certificate Chain");
        jCheckBox1.setEnabled(false);
        CertChainPanel.add(jCheckBox1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        GroupCertPanel.add(CertChainPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        AuthTab.add(GroupCertPanel, gridBagConstraints);

        jTabbedPane1.addTab("Authentication", AuthTab);

        TransportTab.setBackground(new java.awt.Color(190, 190, 226));
        jTabbedPane1.addTab("Transport", TransportTab);

        jTabbedPane1.addTab("Backup Servers", BackupServerTab);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel3.setBackground(new java.awt.Color(190, 190, 226));
        jButton1.setBackground(new java.awt.Color(190, 190, 226));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton1.setText("Save");
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(190, 190, 226));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton2.setText("Cancel");
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NewAccount(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcctLabel;
    private javax.swing.JLabel AcctLabel1;
    private javax.swing.JTextField AcctName;
    private javax.swing.JTextField AcctName1;
    private javax.swing.ButtonGroup AuthButtonGroup;
    private javax.swing.JPanel AuthTab;
    private javax.swing.JPanel BackupServerTab;
    private javax.swing.JPanel CertChainPanel;
    private javax.swing.JLabel CertNameLabel;
    private javax.swing.JTextField DescrField;
    private javax.swing.JLabel DescrLabel;
    private javax.swing.JLabel DescrLabel1;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JPanel EntryPanel;
    private javax.swing.JPanel GroupAuthButtonPanel;
    private javax.swing.JPanel GroupAuthButtonPanel1;
    private javax.swing.JPanel GroupAuthPanel;
    private javax.swing.JPanel GroupCertNamePanel;
    private javax.swing.JPanel GroupCertPanel;
    private javax.swing.JPanel GroupConfirmPassPanel;
    private javax.swing.JPanel GroupNamePanel;
    private javax.swing.JPanel GroupPasswdPanel;
    private javax.swing.JTextField HostField;
    private javax.swing.JLabel HostLabel;
    private javax.swing.JLabel HostLabel1;
    private javax.swing.JPanel HostPanel;
    private javax.swing.JPanel IconPanel;
    private javax.swing.JPanel TransportTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private vpn3k UI;
}
