/*
 * vpnAbout.java
 *
 * Created on November 18, 2003, 11:03 AM
 */

/**
 *
 * @author  pdel
 */
public class vpnAbout extends javax.swing.JDialog {
    
    /** Creates new form vpnAbout */
    public vpnAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
       public vpnAbout() {
        super(new java.awt.Frame(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("About VPN 3000 Client");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setMaximumSize(new java.awt.Dimension(375, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(375, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 50));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ITVpntool  for Solaris and Linux");
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Corporate Software & Services IT / Client Computing Services\n");
        jLabel3.setMaximumSize(new java.awt.Dimension(350, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(350, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(350, 25));
        jPanel2.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(320, 193));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash_screen.png")));
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel1, gridBagConstraints);

        jButton1.setMnemonic('c');
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close(evt);
            }
        });

        ButtonPanel.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(ButtonPanel, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void Close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_Close
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new vpnAbout(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel ButtonPanel;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
