/*
 * vpnSplash.java
 *
 * Created on November 17, 2003, 11:40 PM
 */

/**
 *
 * @author  pdel
 */
public class vpnSplash extends javax.swing.JDialog  {
    
    
    /** Creates new form vpnSplash */
    public vpnSplash(java.awt.Frame parent, boolean modal, long millis ) {
        
        super(parent, modal);
        delay=millis;
        initComponents();
        centerWindow();
        showSplash();
        hideSplash();
    }
    
    public vpnSplash( long millis ){
        
        super( new javax.swing.JFrame(), false );
        
        delay=millis;
        initComponents();
        centerWindow();
        showSplash();
        hideSplash();
        
        
     }
    
    public vpnSplash( vpn3k GUI, long millis ){
        
        super( new javax.swing.JFrame(), false );
        UI=GUI;
        delay=millis;
        initComponents();
        centerWindow();
        showSplash();
        hideSplash();
        return;
        
     }
   
    public void centerWindow(){
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getWidth();
        int height = this.getHeight();
        
        int x = ( dim.width/2 - width/2 );
        int y = ( dim.height/2 - height/2 );
        
        this.setLocation( x, y );
        
    }
    
    public void showSplash(){
        
        show();
    }
    
    public void hideSplash(){
        
        try{
            for ( int i=0; i<delay; i += 100 ){
                //System.out.println( "ctr: " + i );
                Thread.sleep(100);
                if ( closeWindow == true ) {
                    break;
                }
            }
            this.setVisible(false);
            this.dispose();
            
            
        }catch(Exception x ){
        }
       
       return; 
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setForeground(new java.awt.Color(204, 204, 204));
        setName("");
        setResizable(false);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.lightGray), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel1.setMaximumSize(new java.awt.Dimension(375, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(375, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 300));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 50));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ITVpntool for Solaris and Linux");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Corporate Software & Services IT / Client Computing Services\n");
        jLabel3.setMaximumSize(new java.awt.Dimension(350, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(350, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel2.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(325, 225));
        jPanel3.setMinimumSize(new java.awt.Dimension(325, 225));
        jPanel3.setPreferredSize(new java.awt.Dimension(325, 225));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Powered By:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash_screen.png")));
        jLabel1.setMaximumSize(new java.awt.Dimension(305, 195));
        jLabel1.setMinimumSize(new java.awt.Dimension(305, 195));
        jLabel1.setPreferredSize(new java.awt.Dimension(305, 195));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void Close(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close
        // Add your handling code here:
        closeWindow = true;
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_Close
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        long delay;
        
        if ( args.length == 1 ){
            delay = new Integer( args[0] ).longValue();
        } else {
            delay = 5000;
        }
        
        vpnSplash vs =  new vpnSplash(delay);
        System.exit(0);
     }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    private long delay = 1000;
    private vpn3k UI;
    private boolean closeWindow = false;
}
